export type Question = {
  id: number;
  subject: string;
  topic: string;
  question: string;
  options: string[];
  correctAnswer: number;
};

// Expanded question bank for OAU Post-UTME
export const subjectQuestions: Record<string, Question[]> = {
  English: [
    {"id":1001,"subject":"English","topic":"General","question":"Choose the correct sentence: The committee ___ divided in their opinions about the new policy.","options":["are","is","were","have been"],"correctAnswer":2},
    {"id":1002,"subject":"English","topic":"General","question":"Identify the correctly spelt word:","options":["Occassion","Occasion","Ocasión","Ocassion"],"correctAnswer":1},
    {"id":1003,"subject":"English","topic":"General","question":"Select the word nearest in meaning to \"Benevolent\":","options":["Kind","Greedy","Hostile","Selfish"],"correctAnswer":0},
    {"id":1004,"subject":"English","topic":"General","question":"Choose the correct stress pattern for \"Education\":","options":["ED-u-ca-tion","E-DU-ca-tion","Ed-u-CA-tion","Ed-u-ca-TION"],"correctAnswer":2},
    {"id":1005,"subject":"English","topic":"General","question":"Which sentence is grammatically correct?","options":["She don’t like apples.","She doesn’t likes apples.","She doesn’t like apples.","She didn’t likes apples."],"correctAnswer":2},
    {"id":1006,"subject":"English","topic":"General","question":"Choose the correct sentence: Neither the students nor the teacher ___ aware of the sudden test.","options":["was","were","are","have been"],"correctAnswer":0},
    {"id":1007,"subject":"English","topic":"General","question":"Identify the word with the wrong spelling:","options":["Embarrass","Occurence","Millennium","Harass"],"correctAnswer":1},
    {"id":1008,"subject":"English","topic":"General","question":"Select the word opposite in meaning to \"Ephemeral\":","options":["Permanent","Fragile","Temporary","Sudden"],"correctAnswer":0},
    {"id":1009,"subject":"English","topic":"General","question":"Which sentence contains a gerund?","options":["She runs daily.","Running is her hobby.","He will run tomorrow.","They ran quickly."],"correctAnswer":1},
    {"id":1010,"subject":"English","topic":"General","question":"Choose the correct stress pattern for the word \"Photograph\":","options":["PHO-to-graph","pho-TO-graph","pho-to-GRAPH","PHO-to-graph"],"correctAnswer":1},
    {"id":1011,"subject":"English","topic":"General","question":"Pick the odd word out:","options":["Novel","Poetry","Sculpture","Drama"],"correctAnswer":2},
    {"id":1012,"subject":"English","topic":"General","question":"Which is the correct passive voice of: \"They built this house in 1990\"?","options":["This house was built in 1990 by them.","This house is built in 1990 by them.","This house built them in 1990.","This house has been built in 1990."],"correctAnswer":0},
    {"id":1013,"subject":"English","topic":"General","question":"Identify the grammatical function of the underlined word: \"She gave him a book.\"","options":["Direct object","Indirect object","Subject complement","Adverbial phrase"],"correctAnswer":0},
    {"id":1014,"subject":"English","topic":"General","question":"Choose the correct idiom: \"Don’t ___ until you cross it.\"","options":["burn the bridge","build the bridge","cross the bridge","break the bridge"],"correctAnswer":0},
    {"id":1015,"subject":"English","topic":"General","question":"Which word is not a preposition?","options":["Against","Beyond","Quickly","Within"],"correctAnswer":2},
    {"id":1016,"subject":"English","topic":"General","question":"Select the synonym for \"Pragmatic\":","options":["Idealistic","Practical","Theoretical","Unrealistic"],"correctAnswer":1},
    {"id":1017,"subject":"English","topic":"General","question":"Correct the sentence: \"Each of the boys were given a prize.\"","options":["Each of the boys was given a prize.","Each of the boys are given a prize.","Each boys were given a prize.","Each boy were given a prize."],"correctAnswer":0},
    {"id":1018,"subject":"English","topic":"General","question":"Identify the figure of speech: \"Time is a thief.\"","options":["Simile","Metaphor","Personification","Hyperbole"],"correctAnswer":1},
    {"id":1019,"subject":"English","topic":"General","question":"Choose the appropriate question tag: \"She can swim, ___?\"","options":["can’t she","couldn’t she","isn’t it","hasn’t she"],"correctAnswer":0},
    {"id":1020,"subject":"English","topic":"General","question":"Which sentence is punctuated correctly?","options":["\"What time is it\" she asked?","\"What time is it?\" she asked.","\"What time is it,\" she asked?","\"What time is it? she asked.\""],"correctAnswer":1},
    { id: 101, subject: "English", topic: "Lexis", question: "Antonym: The student’s insipid remark annoyed the lecturer.", options: ["Sharp", "Bold", "Tasty", "Interesting"], correctAnswer: 3 },
    { id: 102, subject: "English", topic: "Lexis", question: "Synonym: His demeanour during the trial was calm.", options: ["Background", "Behaviour", "Sentence", "Evidence"], correctAnswer: 1 },
    { id: 103, subject: "English", topic: "Structure", question: "Completion: If I had heard this earlier, I ______ given him the job.", options: ["would not have", "would have not", "will not have", "will have not"], correctAnswer: 0 },
    { id: 104, subject: "English", topic: "Idioms", question: "From the options provided, choose the one nearest in meaning to the idiom: To 'kick the bucket' means to ______.", options: ["Start a fight", "Be clumsy", "Pass away", "Play football"], correctAnswer: 2 },
    { id: 105, subject: "English", topic: "Structure", question: "Choose the correct option: By the time the rainy season ended, the bridge ___________ .", options: ["has been completed", "was completed", "had been completed", "is completed"], correctAnswer: 2 },
    { id: 106, subject: "English", topic: "Structure", question: "Grammar: She is the _____ of the two sisters.", options: ["tallest", "taller", "most tall", "more taller"], correctAnswer: 1 },
    { id: 107, subject: "English", topic: "Lexis", question: "Choose the word that is correctly spelled.", options: ["Accommodation", "Accomodation", "Acommodation", "Acomodation"], correctAnswer: 0 },
    { id: 108, subject: "English", topic: "Structure", question: "Lexis: The committee has submitted its ______.", options: ["report", "reports", "reporting", "reporter"], correctAnswer: 0 },
    { id: 109, subject: "English", topic: "Structure", question: "Structure: Neither the boys nor the girls ______ present.", options: ["was", "were", "is", "has been"], correctAnswer: 1 },
    { id: 110, subject: "English", topic: "Oral English", question: "Choose the word with the same vowel sound as the capitalized letter(s): wOmen", options: ["Woman", "Money", "Village", "Police"], correctAnswer: 2 },
    { id: 111, subject: "English", topic: "Lexis", question: "Synonym: The king was known for his benevolence.", options: ["Cruelty", "Kindness", "Wealth", "Power"], correctAnswer: 1 },
    { id: 112, subject: "English", topic: "Lexis", question: "Antonym: The instructions were quite explicit.", options: ["Clear", "Vague", "Long", "Simple"], correctAnswer: 1 },
    { id: 113, subject: "English", topic: "Idioms", question: "In the sentence, 'The boy turned a deaf ear to his mother's advice', 'turned a deaf ear' means:", options: ["Listened carefully", "Ignored", "Understood", "Paid attention"], correctAnswer: 1 },
    { id: 114, subject: "English", topic: "Structure", question: "Choose the correct option: Neither James nor his friends ___ coming.", options: ["is", "are", "was", "were"], correctAnswer: 1 },
    { id: 115, subject: "English", topic: "Lexis", question: "Identify the correctly spelt word.", options: ["Embarassment", "Embarrasment", "Embarrassment", "Embarasment"], correctAnswer: 2 },
    { id: 116, subject: "English", topic: "Lexis", question: "Synonym: The smell was very pungent.", options: ["Sweet", "Strong", "Faint", "Pleasant"], correctAnswer: 1 },
    { id: 117, subject: "English", topic: "Oral English", question: "Select the word that rhymes with the given word: BOUGH", options: ["Tough", "Dough", "How", "Cough"], correctAnswer: 2 },
    { id: 118, subject: "English", topic: "Structure", question: "Completion: He has been working here ___ 1990.", options: ["for", "since", "from", "at"], correctAnswer: 1 },
    { id: 119, subject: "English", topic: "Structure", question: "Lexis: One of the boys ___ missing.", options: ["is", "are", "were", "have"], correctAnswer: 0 },
    { id: 120, subject: "English", topic: "Structure", question: "Structure: I prefer tea ___ coffee.", options: ["than", "more than", "to", "for"], correctAnswer: 2 }
  ],
  Mathematics: [
    {"id":1021,"subject":"Mathematics","topic":"General","question":"Solve for xx: 3x+5=203x+5=20","options":["3","5","6","7"],"correctAnswer":1},
    {"id":1022,"subject":"Mathematics","topic":"General","question":"If log102=0.3010log102=0.3010, what is log108log108?","options":["0.9030","1.2040","0.6990","1.5050"],"correctAnswer":0},
    {"id":1023,"subject":"Mathematics","topic":"General","question":"The sum of the first 10 natural numbers is:","options":["45","50","55","60"],"correctAnswer":2},
    {"id":1024,"subject":"Mathematics","topic":"General","question":"If x2−5x+6=0x2−5x+6=0, what are the roots?","options":["2, 3","-2, -3","1, 6","-1, -6"],"correctAnswer":0},
    {"id":1025,"subject":"Mathematics","topic":"General","question":"What is the probability of getting an even number when a die is rolled?","options":["1661","1331","1221","2332"],"correctAnswer":2},
    {"id":1026,"subject":"Mathematics","topic":"General","question":"Simplify: 2x2−8x−2x−22x2−8","options":["2x+42x+4","2x−42x−4","x+4x+4","x−4x−4"],"correctAnswer":0},
    {"id":1027,"subject":"Mathematics","topic":"General","question":"If tanθ=34tanθ=43, find sinθsinθ.","options":["3553","4554","5335","5445"],"correctAnswer":0},
    {"id":1028,"subject":"Mathematics","topic":"General","question":"Solve for xx: log2(x)+log2(x−2)=3log2(x)+log2(x−2)=3.","options":["4","6","8","10"],"correctAnswer":0},
    {"id":1030,"subject":"Mathematics","topic":"General","question":"If y=x3−4x2+2x−1y=x3−4x2+2x−1, find dydxdxdy.","options":["3x2−8x+23x2−8x+2","3x2−4x+23x2−4x+2","x2−8x+2x2−8x+2","3x2−8x−13x2−8x−1"],"correctAnswer":0},
    {"id":1031,"subject":"Mathematics","topic":"General","question":"A bag contains 5 red and 3 blue balls. Two balls are drawn at random without replacement. What is the probability both are red?","options":["514145","10282810","3883","5885"],"correctAnswer":0},
    {"id":1032,"subject":"Mathematics","topic":"General","question":"Find the radius of the circle: x2+y2−6x+4y−12=0x2+y2−6x+4y−12=0.","options":["5","6","7","8"],"correctAnswer":0},
    {"id":1033,"subject":"Mathematics","topic":"General","question":"If ab=23ba=32 and bc=45cb=54, find acca.","options":["815158","615156","10121210","12101012"],"correctAnswer":0},
    {"id":1034,"subject":"Mathematics","topic":"General","question":"The 5th term of an arithmetic sequence is 11, and the 9th term is 19. Find the common difference.","options":["2","3","4","5"],"correctAnswer":0},
    {"id":1035,"subject":"Mathematics","topic":"General","question":"Solve the inequality: 3x−7>53x−7>5.","options":["x>4x>4","x<4x<4","x>2x>2","x<2x<2"],"correctAnswer":0},
    {"id":1036,"subject":"Mathematics","topic":"General","question":"Find the area of a triangle with vertices at (1,2)(1,2), (4,5)(4,5), and (6,3)(6,3).","options":["6","7","8","9"],"correctAnswer":0},
    {"id":1038,"subject":"Mathematics","topic":"General","question":"The mean of 5 numbers is 6. If one number is excluded, the mean becomes 5. What is the excluded number?","options":["10","11","12","13"],"correctAnswer":0},
    {"id":1039,"subject":"Mathematics","topic":"General","question":"Find the value of sin30°×cos60°sin30°×cos60°.","options":["1441","1221","3223","1"],"correctAnswer":0},
    {"id":1040,"subject":"Mathematics","topic":"General","question":"The solution to x+1x−2≥0x−2x+1≥0 is:","options":["x≤−1x≤−1 or x>2x>2","x≥−1x≥−1 or x<2x<2","−1≤x<2−1≤x<2","x<−1x<−1 or x≥2x≥2"],"correctAnswer":0},
    { id: 201, subject: "Mathematics", topic: "Algebra", question: "If x - y = 4 and x + y = 10, find the value of x^2 - y^2", options: ["14", "40", "60", "24"], correctAnswer: 1 },
    { id: 202, subject: "Mathematics", topic: "Calculus", question: "Evaluate the limit of (x^2 - 4)/(x - 2) as x approaches 2", options: ["0", "2", "4", "Undefined"], correctAnswer: 2 },
    { id: 203, subject: "Mathematics", topic: "Coordinate Geometry", question: "What is the distance between the points (2, 3) and (-1, -1)?", options: ["3", "4", "5", "7"], correctAnswer: 2 },
    { id: 204, subject: "Mathematics", topic: "Calculus", question: "Find the derivative of y = sin(3x) with respect to x.", options: ["cos(3x)", "3sin(3x)", "3cos(3x)", "-3cos(3x)"], correctAnswer: 2 },
    { id: 205, subject: "Mathematics", topic: "Probability", question: "What is the probability of obtaining a total of 7 when two fair dice are thrown?", options: ["1/6", "1/12", "1/3", "1/4"], correctAnswer: 0 },
    { id: 206, subject: "Mathematics", topic: "Calculus", question: "Integrate 2x dx.", options: ["2", "x^2", "x^2 + C", "2x + C"], correctAnswer: 2 },
    { id: 207, subject: "Mathematics", topic: "Geometry", question: "The interior angles of a regular polygon are 120 degrees each. How many sides does it have?", options: ["6", "5", "8", "10"], correctAnswer: 0 },
    { id: 208, subject: "Mathematics", topic: "Number Systems", question: "Convert 1011 (base 2) to base 10.", options: ["9", "10", "11", "12"], correctAnswer: 2 },
    { id: 209, subject: "Mathematics", topic: "Statistics", question: "Find the mean of 2, 4, 6, 8, 10.", options: ["4", "5", "6", "7"], correctAnswer: 2 },
    { id: 210, subject: "Mathematics", topic: "Logarithms", question: "If log3(x) = -2, find the value of x.", options: ["-6", "1/9", "9", "3/2"], correctAnswer: 1 },
    { id: 211, subject: "Mathematics", topic: "Matrix", question: "Find the determinant of the matrix [[2, 3], [1, 4]].", options: ["5", "8", "6", "11"], correctAnswer: 0 },
    { id: 212, subject: "Mathematics", topic: "Algebra", question: "Solve the inequality: 3 - 2x > 7", options: ["x < -2", "x > -2", "x < 2", "x > 2"], correctAnswer: 0 },
    { id: 213, subject: "Mathematics", topic: "Sequence", question: "Find the 5th term of an AP whose first term is 2 and common difference is 3.", options: ["11", "14", "17", "12"], correctAnswer: 1 },
    { id: 214, subject: "Mathematics", topic: "Geometry", question: "How many sides has a heptagon?", options: ["6", "7", "8", "9"], correctAnswer: 1 },
    { id: 215, subject: "Mathematics", topic: "Permutation", question: "In how many ways can 5 people be seated on a bench?", options: ["60", "120", "240", "10"], correctAnswer: 1 },
    { id: 216, subject: "Mathematics", topic: "Statistics", question: "The median of 1, 3, 5, 7, 9 is?", options: ["3", "5", "7", "9"], correctAnswer: 1 },
    { id: 217, subject: "Mathematics", topic: "Polynomials", question: "Find the remainder when x^3 - 2x^2 + x - 1 is divided by x - 1", options: ["-1", "0", "1", "2"], correctAnswer: 0 },
    { id: 218, subject: "Mathematics", topic: "Mensuration", question: "Calculate the volume of a cylinder of base radius 7cm and height 10cm. (Take pi = 22/7)", options: ["1540 cm^3", "140 cm^3", "770 cm^3", "3080 cm^3"], correctAnswer: 0 },
    { id: 219, subject: "Mathematics", topic: "Geometry", question: "What is the slope of y = 2x + 1?", options: ["1", "2", "-2", "0"], correctAnswer: 1 },
    { id: 220, subject: "Mathematics", topic: "Algebra", question: "Solve for x: x^2 = 144", options: ["12", "144", "24", "10"], correctAnswer: 0 }
  ],
  Economics: [
    { id: 301, subject: "Economics", topic: "Theory of Utility", question: "Utility: At the point of satiety, Marginal Utility is ______.", options: ["Positive", "Increasing", "Zero", "Negative"], correctAnswer: 2 },
    { id: 302, subject: "Economics", topic: "Market Structures", question: "Market: A market with a single seller is a ______.", options: ["Monopoly", "Monopsony", "Oligopoly", "Perfect Market"], correctAnswer: 0 },
    { id: 303, subject: "Economics", topic: "Price Theory", question: "Demand: If price increases and demand remains unchanged, the demand is ______.", options: ["Elastic", "Perfectly Inelastic", "Unitary", "Plastic"], correctAnswer: 1 },
    { id: 304, subject: "Economics", topic: "Economic Systems", question: "A centrally planned economy is also known as ______.", options: ["Mixed", "Capitalist", "Socialist", "Traditional"], correctAnswer: 2 },
    { id: 305, subject: "Economics", topic: "Factors of Production", question: "Which is a factor of production?", options: ["Money", "Labour", "Taxes", "Banks"], correctAnswer: 1 },
    { id: 306, subject: "Economics", topic: "Money and Banking", question: "Inflation means ____.", options: ["Falling prices", "Rising prices", "Stable prices", "Variable prices"], correctAnswer: 1 },
    { id: 307, subject: "Economics", topic: "Factors of Production", question: "The reward for capital is ______.", options: ["Wages", "Rent", "Interest", "Profit"], correctAnswer: 2 },
    { id: 308, subject: "Economics", topic: "Basic Concepts", question: "Opportunity cost is ______.", options: ["Direct cost", "Indirect cost", "Forgone alternative", "Accounting cost"], correctAnswer: 2 },
    { id: 309, subject: "Economics", topic: "Price Theory", question: "Elasticity of supply relates to ____.", options: ["Price and demand", "Price and supply quantity", "Income and supply", "Cost and supply"], correctAnswer: 1 },
    { id: 310, subject: "Economics", topic: "National Income", question: "GDP stands for ______.", options: ["Gross Domestic Product", "Gross Development Product", "Grand Domestic Product", "General Domestic Plan"], correctAnswer: 0 },
    { id: 311, subject: "Economics", topic: "History of Thought", question: "Who is the 'Father of Modern Economics'?", options: ["John Locke", "Adam Smith", "David Ricardo", "John Hicks"], correctAnswer: 1 },
    { id: 312, subject: "Economics", topic: "Public Finance", question: "A deficit budget exists when ____.", options: ["Exp > Rev", "Rev > Exp", "Exp = Rev", "None"], correctAnswer: 0 },
    { id: 313, subject: "Economics", topic: "Price Theory", question: "Price floor is also known as ______.", options: ["Min Price", "Max Price", "Equilibrium", "Shadow Price"], correctAnswer: 0 },
    { id: 314, subject: "Economics", topic: "Market Structures", question: "Which is a characteristic of a perfect market?", options: ["Few sellers", "Many buyers", "Unique products", "Price makers"], correctAnswer: 1 },
    { id: 315, subject: "Economics", topic: "Money and Banking", question: "Money is a medium of ______.", options: ["Exchange", "Savings", "Value", "Wealth"], correctAnswer: 0 }
  ],
  Government: [
    { id: 401, subject: "Government", topic: "History", question: "Republic: Nigeria became a republic in ______.", options: ["1960", "1963", "1970", "1999"], correctAnswer: 1 },
    { id: 402, subject: "Government", topic: "Organs of Govt", question: "Authority: The highest court in Nigeria is the ______.", options: ["High Court", "Court of Appeal", "Supreme Court", "Magistrate Court"], correctAnswer: 2 },
    { id: 403, subject: "Government", topic: "Constitution", question: "Constitution: The 1979 Constitution introduced the ______ system.", options: ["Parliamentary", "Presidential", "Confederal", "Unitary"], correctAnswer: 1 },
    { id: 404, subject: "Government", topic: "International Organizations", question: "OAU was formed in primarily to ______.", options: ["Fight poverty", "Eradicate colonialism", "Promote trade", "Fight diseases"], correctAnswer: 1 },
    { id: 405, subject: "Government", topic: "Political Ideology", question: "The principle of separation of powers prevents ______.", options: ["Democracy", "Dictatorship", "Federalism", "Unitarianism"], correctAnswer: 1 },
    { id: 406, subject: "Government", topic: "Electoral Process", question: "An election held to fill a vacant seat is called a ______.", options: ["General election", "By-election", "Primary election", "Referendum"], correctAnswer: 1 },
    { id: 407, subject: "Government", topic: "Political Ideology", question: "Fascism is closely associated with ______.", options: ["Karl Marx", "Adolf Hitler", "Benito Mussolini", "Joseph Stalin"], correctAnswer: 2 },
    { id: 408, subject: "Government", topic: "International Organizations", question: "The headquarters of ECOWAS is in ______.", options: ["Lagos", "Accra", "Abuja", "Dakar"], correctAnswer: 2 },
    { id: 409, subject: "Government", topic: "Political Concepts", question: "Franchise means the right to ______.", options: ["Vote", "Speak", "Assemble", "Travel"], correctAnswer: 0 },
    { id: 410, subject: "Government", topic: "History", question: "Who was Nigeria's first Prime Minister?", options: ["Nnamdi Azikiwe", "Tafawa Balewa", "Obafemi Awolowo", "Ahmadu Bello"], correctAnswer: 1 },
    { id: 411, subject: "Government", topic: "Political Concepts", question: "The rule of law means ______.", options: ["The king is law", "Equality before law", "Law is optional", "Military rule"], correctAnswer: 1 },
    { id: 412, subject: "Government", topic: "Electoral Process", question: "Gerrymandering is a term in ______.", options: ["Law", "Medicine", "Politics", "Science"], correctAnswer: 2 },
    { id: 413, subject: "Government", topic: "History", question: "The first military coup in Nigeria was in ______.", options: ["1966", "1975", "1983", "1993"], correctAnswer: 0 },
    { id: 414, subject: "Government", topic: "Political Concepts", question: "Power shared between central and state govts is ______.", options: ["Federalism", "Unitarianism", "Confederalism", "Monarchy"], correctAnswer: 0 },
    { id: 415, subject: "Government", topic: "History", question: "Who is the 'father of Nigerian Nationalism'?", options: ["Nnamdi Azikiwe", "Herbert Macaulay", "Obafemi Awolowo", "Ahmadu Bello"], correctAnswer: 1 }
  ],
  Physics: [
    {"id":1041,"subject":"Physics","topic":"General","question":"What is the S.I. unit of force?","options":["Joule","Newton","Watt","Pascal"],"correctAnswer":1},
    {"id":1042,"subject":"Physics","topic":"General","question":"A car accelerates from rest at 2 m/s² for 5 seconds. What is its final velocity?","options":["5 m/s","10 m/s","15 m/s","20 m/s"],"correctAnswer":1},
    {"id":1043,"subject":"Physics","topic":"General","question":"Which of the following is a vector quantity?","options":["Speed","Distance","Velocity","Temperature"],"correctAnswer":2},
    {"id":1044,"subject":"Physics","topic":"General","question":"The refractive index of water is 1.33. What is the speed of light in water?","options":["2.25×108 m/s2.25×108m/s","3.0×108 m/s3.0×108m/s","1.33×108 m/s1.33×108m/s","2.0×108 m/s2.0×108m/s"],"correctAnswer":0},
    {"id":1045,"subject":"Physics","topic":"General","question":"Ohm’s Law states that:","options":["V=IRV=RI","V=IRV=IR","I=VR2I=R2V","R=VI2R=I2V"],"correctAnswer":1},
    {"id":1046,"subject":"Physics","topic":"General","question":"A projectile is fired at an angle of 30° to the horizontal with a velocity of 40 m/s. What is its time of flight? (Take g=10 m/s2g=10m/s2)","options":["2 s","4 s","6 s","8 s"],"correctAnswer":1},
    {"id":1047,"subject":"Physics","topic":"General","question":"Which of the following is NOT a vector quantity?","options":["Force","Velocity","Work","Acceleration"],"correctAnswer":2},
    {"id":1048,"subject":"Physics","topic":"General","question":"The resistance of a wire of length 2 m and cross-sectional area 1×10−6 m21×10−6m2 is 4 Ω4Ω. What is its resistivity?","options":["2×10−6 Ω⋅m2×10−6Ω⋅m","4×10−6 Ω⋅m4×10−6Ω⋅m","6×10−6 Ω⋅m6×10−6Ω⋅m","8×10−6 Ω⋅m8×10−6Ω⋅m"],"correctAnswer":0},
    {"id":1049,"subject":"Physics","topic":"General","question":"A transformer has 500 primary turns and 2500 secondary turns. If the primary voltage is 220 V, what is the secondary voltage?","options":["1100 V","55 V","440 V","2200 V"],"correctAnswer":0},
    {"id":1050,"subject":"Physics","topic":"General","question":"The S.I. unit of capacitance is:","options":["Ohm","Farad","Henry","Tesla"],"correctAnswer":1},
    {"id":1051,"subject":"Physics","topic":"General","question":"A body of mass 5 kg moves with a velocity of 10 m/s. What is its kinetic energy?","options":["50 J","250 J","500 J","1000 J"],"correctAnswer":1},
    {"id":1052,"subject":"Physics","topic":"General","question":"A ray of light travels from air (n=1n=1) to glass (n=1.5n=1.5). If the angle of incidence is 30°, what is the angle of refraction?","options":["19.5°","30°","45°","60°"],"correctAnswer":0},
    {"id":1053,"subject":"Physics","topic":"General","question":"The wavelength of a wave with frequency 500 Hz and speed 50 m/s is:","options":["0.1 m","0.5 m","1.0 m","10 m"],"correctAnswer":0},
    {"id":1054,"subject":"Physics","topic":"General","question":"A gas occupies 2 m³ at 300 K. What volume will it occupy at 600 K if pressure is constant?","options":["1 m³","2 m³","4 m³","6 m³"],"correctAnswer":2},
    {"id":1055,"subject":"Physics","topic":"General","question":"The force between two point charges is 9 N. If the distance between them is tripled, the new force is:","options":["1 N","3 N","9 N","27 N"],"correctAnswer":0},
    {"id":1056,"subject":"Physics","topic":"General","question":"A machine has an efficiency of 80%. If the input work is 500 J, what is the output work?","options":["400 J","500 J","600 J","800 J"],"correctAnswer":0},
    {"id":1057,"subject":"Physics","topic":"General","question":"The critical angle for light passing from glass to air is 41°. What is the refractive index of the glass?","options":["1.52","1.33","1.00","0.75"],"correctAnswer":0},
    {"id":1058,"subject":"Physics","topic":"General","question":"An object is placed 20 cm from a concave mirror of focal length 10 cm. The image distance is:","options":["10 cm","20 cm","30 cm","40 cm"],"correctAnswer":1},
    {"id":1059,"subject":"Physics","topic":"General","question":"The half-life of a radioactive element is 10 days. What fraction remains after 30 days?","options":["1221","1441","1881","116161"],"correctAnswer":2},
    {"id":1060,"subject":"Physics","topic":"General","question":"A 2 kg object is lifted vertically at constant speed through a height of 5 m. The work done against gravity is: (Take g=10 m/s2g=10m/s2)","options":["10 J","50 J","100 J","200 J"],"correctAnswer":2},
    { id: 501, subject: "Physics", topic: "Optics", question: "Optics: The image formed by a plane mirror is ______.", options: ["Real and Inverted", "Virtual and Erect", "Diminished", "Magnified"], correctAnswer: 1 },
    { id: 502, subject: "Physics", topic: "Heat", question: "Heat: The temperature at which water is densest is ______.", options: ["0°C", "4°C", "100°C", "-4°C"], correctAnswer: 1 },
    { id: 503, subject: "Physics", topic: "Electricity", question: "Energy: The unit of electrical power is ______.", options: ["Joule", "Ampere", "Watt", "Volt"], correctAnswer: 2 },
    { id: 504, subject: "Physics", topic: "Mechanics", question: "Acceleration due to gravity is approximately ______.", options: ["9.8 m/s^2", "10.5 m/s^2", "8.9 m/s^2", "12 m/s^2"], correctAnswer: 0 },
    { id: 505, subject: "Physics", topic: "Mechanics", question: "The branch of physics dealing with motion under force is ______.", options: ["Thermodynamics", "Optics", "Mechanics", "Acoustics"], correctAnswer: 2 },
    { id: 506, subject: "Physics", topic: "Mechanics", question: "What is the formula for kinetic energy?", options: ["mgh", "ma", "1/2 mv^2", "F * d"], correctAnswer: 2 },
    { id: 507, subject: "Physics", topic: "Waves", question: "Sound cannot travel through ______.", options: ["Water", "Air", "Vacuum", "Steel"], correctAnswer: 2 },
    { id: 508, subject: "Physics", topic: "Electricity", question: "Resistance is measured in ______.", options: ["Volts", "Ohms", "Amperes", "Coulombs"], correctAnswer: 1 },
    { id: 509, subject: "Physics", topic: "Mechanics", question: "Which is a vector quantity?", options: ["Speed", "Mass", "Velocity", "Distance"], correctAnswer: 2 },
    { id: 510, subject: "Physics", topic: "Modern Physics", question: "The half-life of a radioactive element relates to its ______.", options: ["Mass", "Temperature", "Decay rate", "Density"], correctAnswer: 2 },
    { id: 511, subject: "Physics", topic: "Measurements", question: "Instrument used to measure humidity is ______.", options: ["Barometer", "Hygrometer", "Thermometer", "Ammeter"], correctAnswer: 1 },
    { id: 512, subject: "Physics", topic: "Mechanics", question: "Newton's First Law is also known as of ______.", options: ["Inertia", "Force", "Action", "Gravity"], correctAnswer: 0 },
    { id: 513, subject: "Physics", topic: "Heat", question: "The boiling point of water in Kelvin is ______.", options: ["273 K", "373 K", "100 K", "0 K"], correctAnswer: 1 },
    { id: 514, subject: "Physics", topic: "Optics", question: "Which lens corrects myopia?", options: ["Concave", "Convex", "Bifocal", "Cylindrical"], correctAnswer: 0 },
    { id: 515, subject: "Physics", topic: "Optics", question: "Primary colors of light are ______.", options: ["Red, Blue, Green", "Red, Yellow, Blue", "Orange, Violet, Green", "Black, White, Grey"], correctAnswer: 0 }
  ],
  Chemistry: [
    {"id":1061,"subject":"Chemistry","topic":"General","question":"What is the atomic number of Oxygen?","options":["6","8","10","16"],"correctAnswer":1},
    {"id":1062,"subject":"Chemistry","topic":"General","question":"Which gas is responsible for the smell of rotten eggs?","options":["Methane","Hydrogen Sulphide","Carbon Monoxide","Ammonia"],"correctAnswer":1},
    {"id":1063,"subject":"Chemistry","topic":"General","question":"What is the pH of a neutral solution?","options":["1","7","10","14"],"correctAnswer":1},
    {"id":1064,"subject":"Chemistry","topic":"General","question":"The chemical formula for table salt is:","options":["NaCl","KCl","CaCl₂","MgCl₂"],"correctAnswer":0},
    {"id":1065,"subject":"Chemistry","topic":"General","question":"Which of the following is a halogen?","options":["Sodium","Chlorine","Calcium","Iron"],"correctAnswer":1},
    {"id":1066,"subject":"Chemistry","topic":"General","question":"Which of these elements is a halogen?","options":["Sodium","Magnesium","Chlorine","Argon"],"correctAnswer":2},
    {"id":1067,"subject":"Chemistry","topic":"General","question":"The oxidation number of sulfur in H₂SO₄ is:","options":["+2","+4","+6","-2"],"correctAnswer":2},
    {"id":1068,"subject":"Chemistry","topic":"General","question":"What volume of CO₂ at STP is produced by burning 12g of carbon? (C = 12, molar volume = 22.4 dm³)","options":["11.2 dm³","22.4 dm³","33.6 dm³","44.8 dm³"],"correctAnswer":1},
    {"id":1069,"subject":"Chemistry","topic":"General","question":"Which compound exhibits hydrogen bonding?","options":["CH₄","HCl","NH₃","NaCl"],"correctAnswer":2},
    {"id":1070,"subject":"Chemistry","topic":"General","question":"The IUPAC name for CH₃CH₂CH₂OH is:","options":["Methanol","Ethanol","Propanol","Butanol"],"correctAnswer":2},
    {"id":1071,"subject":"Chemistry","topic":"General","question":"In the electrolysis of molten NaCl, the product at the cathode is:","options":["Cl₂ gas","Na metal","H₂ gas","NaOH"],"correctAnswer":1},
    {"id":1072,"subject":"Chemistry","topic":"General","question":"Which gas is produced when dilute HCl reacts with zinc?","options":["Cl₂","H₂","O₂","N₂"],"correctAnswer":1},
    {"id":1073,"subject":"Chemistry","topic":"General","question":"The pH of 0.001 mol/dm³ HCl solution is:","options":["1","2","3","4"],"correctAnswer":2},
    {"id":1074,"subject":"Chemistry","topic":"General","question":"Which of these is a secondary alcohol?","options":["CH₃OH","CH₃CH₂OH","(CH₃)₂CHOH","(CH₃)₃COH"],"correctAnswer":2},
    {"id":1075,"subject":"Chemistry","topic":"General","question":"The number of neutrons in an atom of ²³₁₁Na is:","options":["11","12","23","34"],"correctAnswer":1},
    {"id":1076,"subject":"Chemistry","topic":"General","question":"Which process is endothermic?","options":["Freezing water","Condensation","Sublimation","Combustion"],"correctAnswer":2},
    {"id":1077,"subject":"Chemistry","topic":"General","question":"The shape of a molecule of methane (CH₄) is:","options":["Linear","Tetrahedral","Trigonal planar","Octahedral"],"correctAnswer":1},
    {"id":1078,"subject":"Chemistry","topic":"General","question":"Which indicator turns yellow in acidic solutions?","options":["Phenolphthalein","Methyl orange","Litmus","Universal indicator"],"correctAnswer":1},
    {"id":1079,"subject":"Chemistry","topic":"General","question":"The empirical formula of C₆H₁₂O₆ is:","options":["CH₂O","C₂H₄O₂","C₃H₆O₃","C₆H₁₂O₆"],"correctAnswer":0},
    {"id":1080,"subject":"Chemistry","topic":"General","question":"In the reaction: N₂ + 3H₂ ⇌ 2NH₃, increasing pressure will:","options":["Favor forward reaction","Favor reverse reaction","Have no effect","Stop the reaction"],"correctAnswer":0},
    { id: 601, subject: "Chemistry", topic: "Gas Laws", question: "Gas Laws: PV = nRT is the equation for ______.", options: ["Ideal Gas", "Boyle's Law", "Charles' Law", "Dalton's Law"], correctAnswer: 0 },
    { id: 602, subject: "Chemistry", topic: "Acids and Bases", question: "Acidity: A solution with a pH of 3 is ______.", options: ["Strongly Acidic", "Weakly Acidic", "Neutral", "Basic"], correctAnswer: 0 },
    { id: 603, subject: "Chemistry", topic: "Chemical Bonding", question: "Bonding: The bond in a Sodium Chloride crystal is ______.", options: ["Covalent", "Ionic", "Metallic", "Dative"], correctAnswer: 1 },
    { id: 604, subject: "Chemistry", topic: "Atomic Structure", question: "The atomic number is the number of ______.", options: ["Neutrons", "Protons", "Electrons", "Nucleons"], correctAnswer: 1 },
    { id: 605, subject: "Chemistry", topic: "Atomic Structure", question: "An isotope has the same number of _____ but different ____.", options: ["protons, electrons", "neutrons, protons", "protons, neutrons", "electrons, neutrons"], correctAnswer: 2 },
    { id: 606, subject: "Chemistry", topic: "Periodic Table", question: "Which is an inert gas?", options: ["Oxygen", "Nitrogen", "Neon", "Fluorine"], correctAnswer: 2 },
    { id: 607, subject: "Chemistry", topic: "Compounds", question: "The formula of sulphuric acid is ______.", options: ["H2SO3", "H2S", "H2SO4", "SO2"], correctAnswer: 2 },
    { id: 608, subject: "Chemistry", topic: "Redox", question: "Reduction is the ______ of electrons.", options: ["Loss", "Gain", "Sharing", "Pairing"], correctAnswer: 1 },
    { id: 609, subject: "Chemistry", topic: "Organic Chemistry", question: "Organic chemistry is primarily the study of ______ compounds.", options: ["Nitrogen", "Oxygen", "Carbon", "Hydrogen"], correctAnswer: 2 },
    { id: 610, subject: "Chemistry", topic: "Elements", question: "Which metal is liquid at standard room temperature?", options: ["Iron", "Lead", "Mercury", "Copper"], correctAnswer: 2 },
    { id: 611, subject: "Chemistry", topic: "Elements", question: "What is the most abundant element in the universe?", options: ["Oxygen", "Carbon", "Hydrogen", "Nitrogen"], correctAnswer: 2 },
    { id: 612, subject: "Chemistry", topic: "Atomic Structure", question: "Valency of Carbon is ______.", options: ["2", "3", "4", "5"], correctAnswer: 2 },
    { id: 613, subject: "Chemistry", topic: "Periodic Table", question: "Which of these is a halogen?", options: ["Neon", "Chlorine", "Argon", "Helium"], correctAnswer: 1 },
    { id: 614, subject: "Chemistry", topic: "Physical States", question: "The process of a solid turning into a gas is ______.", options: ["Evaporation", "Melting", "Sublimation", "Condensation"], correctAnswer: 2 },
    { id: 615, subject: "Chemistry", topic: "Physical States", question: "Rusting of iron requires ______.", options: ["Water only", "Oxygen only", "Water and Oxygen", "Nitrogen"], correctAnswer: 2 }
  ],
  Literature: [
    { id: 701, subject: "Literature", topic: "Figures of Speech", question: "Devices: 'The sun smiled at us' is an example of ______.", options: ["Personification", "Metaphor", "Hyperbole", "Oxymoron"], correctAnswer: 0 },
    { id: 702, subject: "Literature", topic: "Drama", question: "Drama: A play that ended in a disaster for the main character is a ______.", options: ["Comedy", "Tragedy", "Satire", "Farce"], correctAnswer: 1 },
    { id: 703, subject: "Literature", topic: "Poetry", question: "Poetry: A poem of 14 lines is called a ______.", options: ["Sonnet", "Lyric", "Epic", "Ode"], correctAnswer: 0 },
    { id: 704, subject: "Literature", topic: "Prose", question: "A story within a story is called a ______.", options: ["Prologue", "Epilogue", "Frame narrative", "Soliloquy"], correctAnswer: 2 },
    { id: 705, subject: "Literature", topic: "Drama", question: "Which of these is a dramatic genre?", options: ["Prose", "Poetry", "Tragicomedy", "Sonnet"], correctAnswer: 2 },
    { id: 706, subject: "Literature", topic: "Poetry", question: "A stanza of four lines is a ______.", options: ["Couplet", "Quatrain", "Sestet", "Octave"], correctAnswer: 1 },
    { id: 707, subject: "Literature", topic: "Prose", question: "The time and place of a story is its ______.", options: ["Plot", "Setting", "Theme", "Tone"], correctAnswer: 1 },
    { id: 708, subject: "Literature", topic: "Figures of Speech", question: "Simile always involves the use of ______.", options: ["Like or as", "Exaggeration", "Irony", "Rhyme"], correctAnswer: 0 },
    { id: 709, subject: "Literature", topic: "Poetry", question: "A long narrative poem detailing hero's deeds is an ______.", options: ["Ode", "Elegy", "Epic", "Ballad"], correctAnswer: 2 },
    { id: 710, subject: "Literature", topic: "Figures of Speech", question: "Words that sound like their meaning signify ______.", options: ["Alliteration", "Onomatopoeia", "Assonance", "Consonance"], correctAnswer: 1 },
    { id: 711, subject: "Literature", topic: "Drama", question: "A protagonist's fatal flaw is called Hamartia.", options: ["Hamartia", "Catharsis", "Hubris", "Anagnorisis"], correctAnswer: 0 },
    { id: 712, subject: "Literature", topic: "Figures of Speech", question: "A reference to a historical or literary figure is an Allusion.", options: ["Illusion", "Allusion", "Allegory", "Analogy"], correctAnswer: 1 },
    { id: 713, subject: "Literature", topic: "Poetry", question: "Rhyme scheme ABAB is called Alternate rhyme.", options: ["Couplet", "Alternate rhyme", "Monorhyme", "Limerick"], correctAnswer: 1 },
    { id: 714, subject: "Literature", topic: "Poetry", question: "A poem mourning a dead person is an Elegy.", options: ["Ode", "Elegy", "Sonnet", "Epic"], correctAnswer: 1 },
    { id: 715, subject: "Literature", topic: "Figures of Speech", question: "Which of these is a figure of sound?", options: ["Oxymoron", "Simile", "Alliteration", "Irony"], correctAnswer: 2 }
  ],
  CRK: [
    { id: 801, subject: "CRK", topic: "Biblical Characters", question: "Which of these was a prophet?", options: ["David", "Gideon", "Isaiah", "Samson"], correctAnswer: 2 },
    { id: 802, subject: "CRK", topic: "Exodus", question: "Moses received the ten commandments at ____.", options: ["Mount Zion", "Mount Sinai", "Mount Horeb", "Mount Carmel"], correctAnswer: 1 },
    { id: 803, subject: "CRK", topic: "Kingdom of Israel", question: "Who was the first king of Israel?", options: ["David", "Solomon", "Saul", "Samuel"], correctAnswer: 2 },
    { id: 804, subject: "CRK", topic: "Gospels", question: "Jesus was born in ____.", options: ["Nazareth", "Bethlehem", "Jerusalem", "Jericho"], correctAnswer: 1 },
    { id: 805, subject: "CRK", topic: "Gospels", question: "The betrayal of Jesus was done by ____.", options: ["Peter", "Judas Iscariot", "John", "Thomas"], correctAnswer: 1 },
    { id: 806, subject: "CRK", topic: "Acts and Epistles", question: "Which apostle wrote most of the Epistles?", options: ["Peter", "John", "James", "Paul"], correctAnswer: 3 },
    { id: 807, subject: "CRK", topic: "Old Testament", question: "The promised land is ____.", options: ["Egypt", "Canaan", "Babylon", "Assyria"], correctAnswer: 1 },
    { id: 808, subject: "CRK", topic: "Old Testament", question: "Who interpreted Pharaoh's dreams?", options: ["Joseph", "Moses", "Daniel", "Jacob"], correctAnswer: 0 },
    { id: 809, subject: "CRK", topic: "Old Testament", question: "The flood occurred during the time of ____.", options: ["Abraham", "Lot", "Noah", "Enoch"], correctAnswer: 2 },
    { id: 810, subject: "CRK", topic: "Early Church", question: "The first martyr of the early church was ____.", options: ["Peter", "Stephen", "Paul", "James"], correctAnswer: 1 },
    { id: 811, subject: "CRK", topic: "Gospels", question: "How many disciples did Jesus have initially?", options: ["10", "11", "12", "13"], correctAnswer: 2 },
    { id: 812, subject: "CRK", topic: "Biblical General Knowledge", question: "The last book of the Bible is ______.", options: ["Genesis", "Exodus", "Proverbs", "Revelation"], correctAnswer: 3 },
    { id: 813, subject: "CRK", topic: "Biblical Characters", question: "Who was swallowed by a big fish?", options: ["Jonah", "Peter", "Paul", "Moses"], correctAnswer: 0 },
    { id: 814, subject: "CRK", topic: "Biblical General Knowledge", question: "The first book of the Bible is ______.", options: ["Genesis", "Exodus", "Matthew", "John"], correctAnswer: 0 },
    { id: 815, subject: "CRK", topic: "Biblical Characters", question: "Who killed Goliath?", options: ["Saul", "David", "Samson", "Jonathan"], correctAnswer: 1 }
  ]
};

// Fallback for previous import
export const postUtmeQuestions: Question[] = [
  ...subjectQuestions.English,
  ...subjectQuestions.Mathematics,
  ...subjectQuestions.Physics,
  ...subjectQuestions.Chemistry
];
